### ISSUE TITLE
安装使用疑问

### ISSUE THREAD

**Issue by xiaowasly** [Sunnyyoung/Meizi#13]
你好  我在执行了pod install  之后  大约下载了200M的内容 但是打开工程还是会提示我没有更新的错误
:diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
请问是怎么解决呢  有没有完整的工程呢?

**Comment by sunnyyoung** [comment]
@xiaowasly http://code4app.com/article/cocoapods-install-usage
