### ISSUE TITLE
一些新功能建议

### ISSUE THREAD

**Issue by remlostime** [Sunnyyoung/Meizi#14]
@Sunnyyoung 看了一下你的app，感觉挺有意思。感觉还有很多功能值得加入：比如看图片的详细资料：用户id，地区。按地区查看图片等等。
我有一些疑问：
1）请问你是否有加入新功能能的计划
2）我看了代码。你的API用的是meizi.leanapp.cn  请问这个是你自己的服务器吗？
3）如果你愿意，我可否也帮忙来加入新功能

Thanks

**Comment by sunnyyoung** [comment]
@remlostime 
暂时没有增加新功能的计划啦，因为要搬砖
meizi.leanapp.cn 是我自己的服务器，接口比较简单
当然欢迎

**Comment by remlostime** [comment]
Thanks
