### ISSUE TITLE
请教下豆瓣美女的图片你是通过什么方式爬下来的？

### ISSUE THREAD

**Issue by Insfgg99x** [Sunnyyoung/Meizi#15]
如题，请问你是自己用脚本爬下来的呢还是html解析出来的呢

**Comment by sunnyyoung** [comment]
@Insfgg99x 使用 Python 写爬虫定时爬取，数据存放在 LeanCloud

**Comment by Insfgg99x** [comment]
请教下你用的是Lean Cloud REST API吗，Python脚本可以开源出来么？
