### ISSUE TITLE
你好，我发现app总是无法获取图片

### ISSUE THREAD

**Issue by ZsIsMe** [Sunnyyoung/Meizi#2]
http://www.dbmeizi.com 无法访问，怎么办，需要自己搭服务器么？

**Comment by sunnyyoung** [comment]
@ZsIsMe 主站挂掉了咯~~前几天还可以的~

**Comment by allanzhang** [comment]
被黑了？

**Comment by sunnyyoung** [comment]
@allanzhang 不知道呀，最近没空=。= 等有空了就更新一下图片源还有这个APP

**Comment by sunnyyoung** [comment]
@allanzhang 已经更新了新版啊哈
